# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testDB2
    username: admin
    password: admin

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.jr: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO