version: "3.1"

services:
    database:
        image: library/postgres:12.4
        restart: always
        ports: [ "5432:5432" ]
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        logging:
            driver: "none"

    adminer:
        image: library/adminer:4.7.7
        restart: always
        ports: [ "8081:8080" ]
        logging:
            driver: "none"